site_name: Tremor Usage Guide
site_author: The Tremor Team
repo_url: https://git.csnzoo.com/tremor/tremor-runtime
repo_name: data-engeering/tremor-runtime
edit_uri: edit/master/docs
docs_dir: docs
site_dir: html
pages:
#  - Home: index.md
#  - Configuration: Configuration.md
theme:
  name: material
  logo: img/logo.png
extra:
  repo_icon: gitlab
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
nav:
  - Home: index.md
  - 'Architecture Overview': overview.md
  - Tremor Script:
    - Overview: tremor-script/index.md
    - Function Reference:
      - Overview: tremor-script/functions.md
      - array: tremor-script/functions/array.md
      - chash: tremor-script/functions/chash.md
      - datetime: tremor-script/functions/datetime.md
      - integer: tremor-script/functions/integer.md
      - json: tremor-script/functions/json.md
      - math: tremor-script/functions/math.md
      - random: tremor-script/functions/random.md
      - record: tremor-script/functions/record.md
      - re: tremor-script/functions/re.md
      - string: tremor-script/functions/string.md
      - system: tremor-script/functions/system.md
      - type: tremor-script/functions/type.md
    - Extractor Reference:
      -  Overview: tremor-script/extractors.md
      -  Base64: tremor-script/extractors/base64.md
      -  CIDR: tremor-script/extractors/cidr.md
      -  Datetime: tremor-script/extractors/datetime.md
      -  Dissect: tremor-script/extractors/dissect.md
      -  Glob: tremor-script/extractors/glob.md
      -  Grok: tremor-script/extractors/grok.md
      -  Influx: tremor-script/extractors/influx.md
      -  JSON: tremor-script/extractors/json.md
      -  KV: tremor-script/extractors/kv.md
      -  Regex: tremor-script/extractors/regex.md
    - Recipes: tremor-script/recipes.md
  - Operations:
    - Configuration: operations/configuration.md
    - Monitoring: operations/monitoring.md
    - Tremor Tool: operations/cli.md
    - Configuration Walkthrough: operations/configuration-walkthrough.md
  - Artefacts:
    - Preprocessors: artefacts/preprocessors.md
    - Postprocessors: artefacts/postprocessors.md
    - Codecs: artefacts/codecs.md
    - Onramps: artefacts/onramps.md
    - Offramps: artefacts/offramps.md
    - Operators: artefacts/operators.md
  - Development:
    - 'Quick Start Guide': development/quick-start.md
    - Profiling: development/profiling.md
    - 'Debugging with LLDB': development/debugging.md
    - Benchmarking:
      - Overview: development/benchmarking.md
      - Logstash: development/benchmarks/LogstashBenchmark.md
    - Testing: development/testing.md
    - Investigation: development/issue-investigation.md
  - API: api.md
  - History: history.md
  - 'Glossary': Glossary.md
