onramp:
  - id: in
    type: file
    config:
      source: {in}
      close_on_done: true

offramp:
  - id: out
    type: file
    config:
      file: {out}

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
    nodes:
      - id: r1
        op: runtime::tremor
        config:
          script: |
            let $class = "default";
            let $dimensions = match record::contains(event, "application") of
              case true => event.application
              default =>  null
            end;
            let $rate = 5;
            event;
      - id: b1
        op: grouper::bucket
      - id: r2
        op: runtime::tremor
        config:
          script: |
            match record::contains(event, "host") of
              case true => let $dimensions = event.host
              default => null
            end;
            let $rate = 1;
            event;
      - id: b2
        op: grouper::bucket
    links:
      in: [ r1 ]
      r1: [ b1 ]
      b1: [ r2 ]
      r2: [ b2 ]
      b2: [ out ]

binding:
  - id: test
    links:
      '/onramp/in/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/out/{instance}/in' ]
