---
deployments:
  - id: logging
    description: Filtering of applog and syslog streams
    bindings:
      onramps:
        - onramp::blaster:
            id: blaster
            source: ./demo/data/data.json.xz
      offramps:
        - offramp::blackhole:
            id: blackhole
            warmup_secs: 10
            stop_after_secs: 40
            significant_figures: 2
            
links:
  /deployments/logging/blaster: /pipelines/main/in
  /pipelines/main/out: /deployments/logging/out

pipelines:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
    nodes:
      - parse:
          type: parse::json
      - classify:
          type: runtime::mimir
          rules: |

            import imported_var;
            export classification, dimension, rate, index_type;

            _ { $index_type := index; }

            application="app1" { $classification := "applog_app1"; $rate := 1250;  }
            application="app2" { $classification := "applog_app2"; $rate := 2500;  }
            application="app3" { $classification := "applog_app3"; $rate := 18750; }
            application="app4" { $classification := "applog_app4"; $rate := 750;   }
            application="app5" { $classification := "applog_app5"; $rate := 18750; }
            $classification { $dimension := application; return; }

            index_type="applog_app6" { $dimension := logger_name; $classification := "applog_app6"; $rate := 4500; return; }

            index_type="syslog_app1" { $classification := "syslog_app1"; $rate := 2500; }
            tags:"tag1" { $classification := "syslog_app2"; $rate := 125; }
            index_type="syslog_app2" { $classification := "syslog_app2"; $rate := 125; }
            index_type="syslog_app3" { $classification := "syslog_app3"; $rate := 1750; }
            index_type="syslog_app4" { $classification := "syslog_app4"; $rate := 1750; }
            index_type="syslog_app5" { $classification := "syslog_app5"; $rate := 7500; }
            index_type="syslog_app6" { $classification := "syslog_app6"; $rate := 125; }
            $classification { $dimension := syslog_hostname; return; }

            index_type="edilog" { $classification := "edilog"; $dimension := syslog_hostname; $rate := 3750; return; }
            index_type="sqlserverlog" { $classification := "sqlserverlog"; $dimension := [src_ip, dst_ip]; $rate := 125; return; }
            type="applog" { $classification := "applog"; $dimension := [src_ip, dst_ip]; $rate := 75; return; }

            _ { $classification := "default"; $rate := 250; }


      - bucket:
          type: grouper::bucket
          class_key: classification
          dim_key: dimension
          rate_key: rate
      - render:
        type: render::json
    links:
      parse: classify
      classify: bucket
      bucket: render
    imports:
      in: parse/in
    exports:
      out:
        - render/out
