[package]
name = "tremor-pipeline"
version = "0.8.0"
description = "Tremor Pipeline DAG Runtime"
authors = ["The Tremor Team"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
byteorder = "1"
serde = "1"
serde_derive = "1"
simd-json = {version = "0.3", features = ["known-key"] }
simd-json-derive = "0.1"
serde_yaml = "0.8"
petgraph = "0.5"
error-chain="0.12"
tremor-script = { path = "../tremor-script" }
tremor-influx = { path = "../tremor-influx" }
lazy_static = "1"
window = { git = "https://github.com/tremor-rs/window.git",  tag = "v0.1.1"}
indexmap = { version = "1", features=["serde-1"] }
lru = "0.6"
halfbrown = "0.1"
log = "0.4"
rental = "0.5"
regex = "1"
sled = "0.31"

[dev-dependencies]
criterion = "0.3"
xz2 = "0.1"
base64 = "0.12"
