[package]
authors = ["The Tremor Team"]
description = "Tremor Pipeline DAG Runtime"
edition = "2018"
license = "Apache-2.0"
name = "tremor-pipeline"
version = "0.11.1"

[dependencies]
beef = {version = "0.5", features = ["impl_serde"]}
byteorder = "1"
error-chain = "0.12"
halfbrown = "0.1"
indexmap = {version = "1", features = ["serde-1"]}
lazy_static = "1"
log = "0.4"
lru = "0.6"
petgraph = "0.5"
regex = "1"
rental = "0.5"
rust-bert = {version = "0.10.0", optional = true}
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
simd-json = {version = "0.4", features = ["known-key"]}
simd-json-derive = "0.2"
sled = "0.34"
tremor-common = {path = "../tremor-common"}
tremor-influx = {path = "../tremor-influx"}
tremor-script = {path = "../tremor-script"}
url = "2.2.1"
value-trait = "0.2"
window = {git = "https://github.com/tremor-rs/window.git", tag = "v0.1.1"}

[dev-dependencies]
base64 = "0.13"
criterion = "0.3"
tempfile = "3.2"
xz2 = "0.1"

[features]
bert = ["rust-bert"]
