[package]
authors = ["The Tremor Team"]
description = "Tremor Pipeline DAG Runtime"
edition = "2018"
license = "Apache-2.0"
name = "tremor-pipeline"
version = "0.8.0"

[dependencies]
byteorder = "1"
error-chain = "0.12"
halfbrown = "0.1"
indexmap = {version = "1", features = ["serde-1"]}
lazy_static = "1"
log = "0.4"
lru = "0.6"
petgraph = "0.5"
regex = "1"
rental = "0.5"
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
simd-json = {version = "0.3", features = ["known-key"]}
simd-json-derive = "0.1"
sled = "0.34"
tremor-influx = {path = "../tremor-influx"}
tremor-script = {path = "../tremor-script"}
url = "2.1.1"
value-trait = "0.1"
window = {git = "https://github.com/tremor-rs/window.git", tag = "v0.1.1"}

rust-bert = {version = "0.10.0", optional = true}

[dev-dependencies]
base64 = "0.13"
criterion = "0.3"
xz2 = "0.1"

[features]
tremor-bert = ["rust-bert"]

[patch.crates-io]
rust-bert = {git = 'https://github.com/mfelsche/rust-bert.git', rev = '1140989'}
rust_tokenizers = {git = 'https://github.com/mfelsche/rust-tokenizers.git', rev = '5a7860d'}
