onramp:
  - id: in
    type: file
    codec: string
    config:
      source: {in}
      close_on_done: true

offramp:
  - id: out
    type: file
    config:
      file: {out}

pipeline:
  - id: main
    interface:
      inputs:
        - in
      outputs:
        - out
    nodes:
      - id: r
        op: runtime::tremor
        config:
          script: |
            let in = {"message": event};
            let event =  match in of
              case r = %{ message ~= dissect|%{first} %{last}| } => r.message
              default => drop
            end;
            event
    links:
      in: [ r ]
      r: [ out ]

binding:
  - id: test
    links:
      '/onramp/in/{instance}/out': [ '/pipeline/main/{instance}/in' ]
      '/pipeline/main/{instance}/out': [ '/offramp/out/{instance}/in' ]

