[package]
name = "tremor-api"
version = "0.9.0"
description = "Tremor Api Callbacks"
authors = ["The Tremor Team"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
tremor-pipeline = { path = "../tremor-pipeline" }
tremor-script = { path = "../tremor-script" }
tremor-runtime = { path = "../" }
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
hashbrown = { version = "0.9", features = ["serde"] }
tide = "0.13"
http-types = "2.8"
simd-json = "0.3"
