[package]
name = "tremor-api"
version = "0.1.0"
authors = ["Darach Ennis <dennis@wayfair.com>"]
edition = "2018"

[dependencies]
tremor-pipeline = { path = "../tremor-pipeline" }
tremor-runtime = { path = "../" }
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.8"
log = "0.4"
actix-web = "1"
hashbrown = { version = "0.6", features = ["serde"] }
