[package]
authors = ["The Tremor Team"]
description = "Tremor Api Callbacks"
edition = "2018"
license = "Apache-2.0"
name = "tremor-api"
version = "0.11.3"

[dependencies]
hashbrown = {version = "0.11", features = ["serde"]}
http-types = "2.11"
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
simd-json = "0.4"
tide = "0.16"
tremor-pipeline = {path = "../tremor-pipeline"}
tremor-runtime = {path = "../"}
tremor-script = {path = "../tremor-script"}
