[package]
authors = ["The Tremor Team"]
description = "Tremor Api Callbacks"
edition = "2018"
license = "Apache-2.0"
name = "tremor-api"
version = "0.11.4"

[dependencies]
async-channel = "1"
async-std = { version = "1.9.0", features = [
	"unstable",
	"attributes",
	"tokio03",
	"tokio1",
] }
hashbrown = { version = "0.11", features = ["serde"] }
http-types = "2.12"
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
simd-json = "0.4"
tide = "0.16"
tremor-pipeline = { path = "../tremor-pipeline" }
tremor-runtime = { path = "../" }
tremor-script = { path = "../tremor-script" }
