[package]
authors = ["The Tremor Team"]
description = "Tremor Api Callbacks"
edition = "2021"
license = "Apache-2.0"
name = "tremor-api"
version = "0.11.4"

[dependencies]
async-std = { version = "1.10.0", features = [
	"unstable",
	"attributes",
	"tokio03",
	"tokio1",
] }
halfbrown = "0.1"
http-types = "2.12"
log = "0.4"
serde = "1"
serde_derive = "1"
serde_yaml = "0.8"
simd-json = "0.4"
# we don't need sessions or cookies or shitty logging middleware
tide = { version = "0.16", default-features = false, features = ["h1-server"]}
tremor-pipeline = { path = "../tremor-pipeline" }
tremor-runtime = { path = "../" }
tremor-script = { path = "../tremor-script" }
#tremor-value = { path = "../tremor-value" }
tremor-common = { path = "../tremor-common" }
# value-trait = "0.2"
