[package]
name = "tremor-api"
version = "0.7.3"
description = "Tremor Api Callbacks"
authors = ["The Tremor Team"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
tremor-pipeline = { path = "../tremor-pipeline" }
tremor-runtime = { path = "../" }
serde = "1"
serde_derive = "1"
serde_json = "1"
serde_yaml = "0.8"
hashbrown = { version = "0.7", features = ["serde"] }
tide = "0.7"
http = "0.2.1"
http-types = "1.2"
