[package]
authors = ["The Tremor Team"]
description = "Tremor common functions"
documentation = "https://docs.rs/tremor-commons"
edition = "2018"
license = "Apache-2.0"
name = "tremor-common"
readme = "README.md"
version = "0.9.4"

[dependencies]
async-std = "1"
