name: EQC Tests

on: [push]

jobs:
  api:
    if: github.repository_owner == 'tremor-rs' && github.actor!= 'dependabot[bot]'
    runs-on: ubuntu-20.04
    steps:
      - name: Verify valid EQC_LICENSE
        run: test -n "${{secrets.EQC_LICENSE}}"
      - uses: actions/checkout@v1.0.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 23.1
      - name: Install deps
        run: sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1
      - name: install yq
        run: wget https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64 -O ~/yq && chmod +x ~/yq
      - name: install EQC
        run: curl -O http://quviq-licencer.com/downloads/eqcR23.zip && unzip eqcR23.zip && cd Quviq* && sudo erl -noshell -eval 'eqc_install:install()' -eval 'init:stop()'
      - name: Activate EQC
        run: test -n "${{secrets.EQC_LICENSE}}" && erl -noshell -eval 'eqc:registration("${{secrets.EQC_LICENSE}}")' -eval "eqc:start()" -eval "init:stop()"
      - name: generate yaml
        run: ~/yq -o=json static/openapi.yaml > static/openapi.json
      - name: Build
        run: cargo build --all
      - name: Run eqc tests
        run: ./.github/checks/eqc.sh
  tremor-script:
    if: github.repository_owner == 'tremor-rs' && github.actor!= 'dependabot[bot]'
    runs-on: ubuntu-20.04
    steps:
      - name: Verify valid EQC_LICENSE
        run: test -n "${{secrets.EQC_LICENSE}}"
      - uses: actions/checkout@v1.0.0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
      - uses: Swatinem/rust-cache@v1
      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 23.1
      - name: Install deps
        run: sudo apt-get -qy update && sudo apt-get install -y libssl-dev libssl1.1
      - name: install EQC
        run: curl -O http://quviq-licencer.com/downloads/eqcR23.zip && unzip eqcR23.zip && cd Quviq* && sudo erl -noshell -eval 'eqc_install:install()' -eval 'init:stop()'
      - name: Activate EQC
        run: erl -noshell -eval 'eqc:registration("${{secrets.EQC_LICENSE}}")' -eval "eqc:start()" -eval "init:stop()"
      - name: Run
        run: make -C tremor-script run-eqc
