name: Publish Docker - Edge
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to GH Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tremor-rs/tremor-runtime/tremor
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}
          tags: edge
          registry: docker.pkg.github.com
      - name: Publish to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tremorproject/tremor
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: edge
