[package]
authors = ["The Tremor Team"]
description = "Tremor Script Interpreter"
documentation = "https://docs.rs/tremor-script"
edition = "2018"
license = "Apache-2.0"
name = "tremor-value"
readme = "README.md"
version = "0.2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13"
beef = "0.5"
halfbrown = "0.1"
serde = "1.0"
simd-json = "0.3"
simd-json-derive = "0.1"
value-trait = {version = "0.1", features = ["custom-types"]}

[dev-dependencies]
float-cmp = "0.8"
getopts = "0.2"
proptest = "0.10"
serde = {version = "1", features = ["derive"]}
serde_json = "1"

[features]
128bit = []
